/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupSuccessRouteImport } from './routes/signup-success'
import { Route as SignupFormRouteImport } from './routes/signup-form'
import { Route as PosicionesRouteImport } from './routes/posiciones'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiTeamPdfRouteImport } from './routes/api/team-pdf'
import { Route as ApiEventPdfRouteImport } from './routes/api/event-pdf'
import { Route as authenticatedSettingsRouteImport } from './routes/(authenticated)/settings'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedSeasonsIndexRouteImport } from './routes/(authenticated)/seasons/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as authenticatedSeasonsSeasonIdRouteRouteImport } from './routes/(authenticated)/seasons/$seasonId/route'
import { Route as authenticatedSeasonsSeasonIdIndexRouteImport } from './routes/(authenticated)/seasons/$seasonId/index'
import { Route as authenticatedSeasonsSeasonIdTeamsRouteImport } from './routes/(authenticated)/seasons/$seasonId/teams'
import { Route as authenticatedSeasonsSeasonIdScorecardRouteImport } from './routes/(authenticated)/seasons/$seasonId/scorecard'
import { Route as authenticatedSeasonsSeasonIdPlayoffsRouteImport } from './routes/(authenticated)/seasons/$seasonId/playoffs'
import { Route as authenticatedSeasonsSeasonIdGenerateRouteImport } from './routes/(authenticated)/seasons/$seasonId/generate'
import { Route as authenticatedSeasonsSeasonIdConfigureRouteImport } from './routes/(authenticated)/seasons/$seasonId/configure'
import { Route as authenticatedSeasonsSeasonIdBuildRouteImport } from './routes/(authenticated)/seasons/$seasonId/build'
import { Route as authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport } from './routes/(authenticated)/seasons/$seasonId/playoffs_.build'

const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup-success',
  path: '/signup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupFormRoute = SignupFormRouteImport.update({
  id: '/signup-form',
  path: '/signup-form',
  getParentRoute: () => rootRouteImport,
} as any)
const PosicionesRoute = PosicionesRouteImport.update({
  id: '/posiciones',
  path: '/posiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamPdfRoute = ApiTeamPdfRouteImport.update({
  id: '/api/team-pdf',
  path: '/api/team-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventPdfRoute = ApiEventPdfRouteImport.update({
  id: '/api/event-pdf',
  path: '/api/event-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSettingsRoute = authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsIndexRoute =
  authenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSeasonsSeasonIdRouteRoute =
  authenticatedSeasonsSeasonIdRouteRouteImport.update({
    id: '/seasons/$seasonId',
    path: '/seasons/$seasonId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdIndexRoute =
  authenticatedSeasonsSeasonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdTeamsRoute =
  authenticatedSeasonsSeasonIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdScorecardRoute =
  authenticatedSeasonsSeasonIdScorecardRouteImport.update({
    id: '/scorecard',
    path: '/scorecard',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdPlayoffsRoute =
  authenticatedSeasonsSeasonIdPlayoffsRouteImport.update({
    id: '/playoffs',
    path: '/playoffs',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdGenerateRoute =
  authenticatedSeasonsSeasonIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdConfigureRoute =
  authenticatedSeasonsSeasonIdConfigureRouteImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdBuildRoute =
  authenticatedSeasonsSeasonIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdPlayoffsBuildRoute =
  authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport.update({
    id: '/playoffs_/build',
    path: '/playoffs/build',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/settings': typeof authenticatedSettingsRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/seasons/': typeof authenticatedSeasonsIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/seasons/$seasonId/': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/playoffs/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/settings': typeof authenticatedSettingsRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/seasons': typeof authenticatedSeasonsIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/playoffs/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(authenticated)/settings': typeof authenticatedSettingsRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/(authenticated)/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/seasons/': typeof authenticatedSeasonsIndexRoute
  '/(authenticated)/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/(authenticated)/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/(authenticated)/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/(authenticated)/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/(authenticated)/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/(authenticated)/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/(authenticated)/seasons/$seasonId/': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/(authenticated)/seasons/$seasonId/playoffs_/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipos'
    | '/posiciones'
    | '/signup-form'
    | '/signup-success'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/settings'
    | '/api/event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/seasons/$seasonId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/'
    | '/seasons/'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId/playoffs'
    | '/seasons/$seasonId/scorecard'
    | '/seasons/$seasonId/teams'
    | '/seasons/$seasonId/'
    | '/seasons/$seasonId/playoffs/build'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipos'
    | '/posiciones'
    | '/signup-form'
    | '/signup-success'
    | '/login'
    | '/signup'
    | '/settings'
    | '/api/event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard'
    | '/seasons'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId/playoffs'
    | '/seasons/$seasonId/scorecard'
    | '/seasons/$seasonId/teams'
    | '/seasons/$seasonId'
    | '/seasons/$seasonId/playoffs/build'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/equipos'
    | '/posiciones'
    | '/signup-form'
    | '/signup-success'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/(authenticated)/settings'
    | '/api/event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/(authenticated)/seasons/$seasonId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/seasons/'
    | '/(authenticated)/seasons/$seasonId/build'
    | '/(authenticated)/seasons/$seasonId/configure'
    | '/(authenticated)/seasons/$seasonId/generate'
    | '/(authenticated)/seasons/$seasonId/playoffs'
    | '/(authenticated)/seasons/$seasonId/scorecard'
    | '/(authenticated)/seasons/$seasonId/teams'
    | '/(authenticated)/seasons/$seasonId/'
    | '/(authenticated)/seasons/$seasonId/playoffs_/build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  EquiposRoute: typeof EquiposRoute
  PosicionesRoute: typeof PosicionesRoute
  SignupFormRoute: typeof SignupFormRoute
  SignupSuccessRoute: typeof SignupSuccessRoute
  ApiEventPdfRoute: typeof ApiEventPdfRoute
  ApiTeamPdfRoute: typeof ApiTeamPdfRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-success': {
      id: '/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-form': {
      id: '/signup-form'
      path: '/signup-form'
      fullPath: '/signup-form'
      preLoaderRoute: typeof SignupFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posiciones': {
      id: '/posiciones'
      path: '/posiciones'
      fullPath: '/posiciones'
      preLoaderRoute: typeof PosicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-pdf': {
      id: '/api/team-pdf'
      path: '/api/team-pdf'
      fullPath: '/api/team-pdf'
      preLoaderRoute: typeof ApiTeamPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event-pdf': {
      id: '/api/event-pdf'
      path: '/api/event-pdf'
      fullPath: '/api/event-pdf'
      preLoaderRoute: typeof ApiEventPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/': {
      id: '/(authenticated)/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof authenticatedSeasonsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/seasons/$seasonId': {
      id: '/(authenticated)/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/': {
      id: '/(authenticated)/seasons/$seasonId/'
      path: '/'
      fullPath: '/seasons/$seasonId/'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/teams': {
      id: '/(authenticated)/seasons/$seasonId/teams'
      path: '/teams'
      fullPath: '/seasons/$seasonId/teams'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdTeamsRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/scorecard': {
      id: '/(authenticated)/seasons/$seasonId/scorecard'
      path: '/scorecard'
      fullPath: '/seasons/$seasonId/scorecard'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdScorecardRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/playoffs': {
      id: '/(authenticated)/seasons/$seasonId/playoffs'
      path: '/playoffs'
      fullPath: '/seasons/$seasonId/playoffs'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdPlayoffsRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/generate': {
      id: '/(authenticated)/seasons/$seasonId/generate'
      path: '/generate'
      fullPath: '/seasons/$seasonId/generate'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdGenerateRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/configure': {
      id: '/(authenticated)/seasons/$seasonId/configure'
      path: '/configure'
      fullPath: '/seasons/$seasonId/configure'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdConfigureRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/build': {
      id: '/(authenticated)/seasons/$seasonId/build'
      path: '/build'
      fullPath: '/seasons/$seasonId/build'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdBuildRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/playoffs_/build': {
      id: '/(authenticated)/seasons/$seasonId/playoffs_/build'
      path: '/playoffs/build'
      fullPath: '/seasons/$seasonId/playoffs/build'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedSeasonsSeasonIdRouteRouteChildren {
  authenticatedSeasonsSeasonIdBuildRoute: typeof authenticatedSeasonsSeasonIdBuildRoute
  authenticatedSeasonsSeasonIdConfigureRoute: typeof authenticatedSeasonsSeasonIdConfigureRoute
  authenticatedSeasonsSeasonIdGenerateRoute: typeof authenticatedSeasonsSeasonIdGenerateRoute
  authenticatedSeasonsSeasonIdPlayoffsRoute: typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  authenticatedSeasonsSeasonIdScorecardRoute: typeof authenticatedSeasonsSeasonIdScorecardRoute
  authenticatedSeasonsSeasonIdTeamsRoute: typeof authenticatedSeasonsSeasonIdTeamsRoute
  authenticatedSeasonsSeasonIdIndexRoute: typeof authenticatedSeasonsSeasonIdIndexRoute
  authenticatedSeasonsSeasonIdPlayoffsBuildRoute: typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
}

const authenticatedSeasonsSeasonIdRouteRouteChildren: authenticatedSeasonsSeasonIdRouteRouteChildren =
  {
    authenticatedSeasonsSeasonIdBuildRoute:
      authenticatedSeasonsSeasonIdBuildRoute,
    authenticatedSeasonsSeasonIdConfigureRoute:
      authenticatedSeasonsSeasonIdConfigureRoute,
    authenticatedSeasonsSeasonIdGenerateRoute:
      authenticatedSeasonsSeasonIdGenerateRoute,
    authenticatedSeasonsSeasonIdPlayoffsRoute:
      authenticatedSeasonsSeasonIdPlayoffsRoute,
    authenticatedSeasonsSeasonIdScorecardRoute:
      authenticatedSeasonsSeasonIdScorecardRoute,
    authenticatedSeasonsSeasonIdTeamsRoute:
      authenticatedSeasonsSeasonIdTeamsRoute,
    authenticatedSeasonsSeasonIdIndexRoute:
      authenticatedSeasonsSeasonIdIndexRoute,
    authenticatedSeasonsSeasonIdPlayoffsBuildRoute:
      authenticatedSeasonsSeasonIdPlayoffsBuildRoute,
  }

const authenticatedSeasonsSeasonIdRouteRouteWithChildren =
  authenticatedSeasonsSeasonIdRouteRoute._addFileChildren(
    authenticatedSeasonsSeasonIdRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  authenticatedSettingsRoute: typeof authenticatedSettingsRoute
  authenticatedSeasonsSeasonIdRouteRoute: typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  authenticatedSeasonsIndexRoute: typeof authenticatedSeasonsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  authenticatedSettingsRoute: authenticatedSettingsRoute,
  authenticatedSeasonsSeasonIdRouteRoute:
    authenticatedSeasonsSeasonIdRouteRouteWithChildren,
  authenticatedSeasonsIndexRoute: authenticatedSeasonsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  EquiposRoute: EquiposRoute,
  PosicionesRoute: PosicionesRoute,
  SignupFormRoute: SignupFormRoute,
  SignupSuccessRoute: SignupSuccessRoute,
  ApiEventPdfRoute: ApiEventPdfRoute,
  ApiTeamPdfRoute: ApiTeamPdfRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
