/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupFormRouteImport } from './routes/signup-form'
import { Route as SignupSuccessRouteImport } from './routes/signup-success'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiTeamPdfRouteImport } from './routes/api/team-pdf'
import { Route as authenticatedSettingsRouteImport } from './routes/(authenticated)/settings'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedTeamsIndexRouteImport } from './routes/(authenticated)/teams/index'
import { Route as authenticatedSeasonsIndexRouteImport } from './routes/(authenticated)/seasons/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as authenticatedSeasonsSeasonIdIndexRouteImport } from './routes/(authenticated)/seasons/$seasonId/index'
import { Route as authenticatedSeasonsSeasonIdGenerateRouteImport } from './routes/(authenticated)/seasons/$seasonId/generate'
import { Route as authenticatedSeasonsSeasonIdConfigureRouteImport } from './routes/(authenticated)/seasons/$seasonId/configure'
import { Route as authenticatedSeasonsSeasonIdBuildRouteImport } from './routes/(authenticated)/seasons/$seasonId/build'

const SignupFormRoute = SignupFormRouteImport.update({
  id: '/signup-form',
  path: '/signup-form',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup-success',
  path: '/signup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamPdfRoute = ApiTeamPdfRouteImport.update({
  id: '/api/team-pdf',
  path: '/api/team-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSettingsRoute = authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedTeamsIndexRoute = authenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedSeasonsIndexRoute =
  authenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSeasonsSeasonIdIndexRoute =
  authenticatedSeasonsSeasonIdIndexRouteImport.update({
    id: '/seasons/$seasonId/',
    path: '/seasons/$seasonId/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdGenerateRoute =
  authenticatedSeasonsSeasonIdGenerateRouteImport.update({
    id: '/seasons/$seasonId/generate',
    path: '/seasons/$seasonId/generate',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdConfigureRoute =
  authenticatedSeasonsSeasonIdConfigureRouteImport.update({
    id: '/seasons/$seasonId/configure',
    path: '/seasons/$seasonId/configure',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdBuildRoute =
  authenticatedSeasonsSeasonIdBuildRouteImport.update({
    id: '/seasons/$seasonId/build',
    path: '/seasons/$seasonId/build',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/settings': typeof authenticatedSettingsRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/seasons': typeof authenticatedSeasonsIndexRoute
  '/teams': typeof authenticatedTeamsIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipos': typeof EquiposRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/settings': typeof authenticatedSettingsRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/seasons': typeof authenticatedSeasonsIndexRoute
  '/teams': typeof authenticatedTeamsIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/equipos': typeof EquiposRoute
  '/signup-form': typeof SignupFormRoute
  '/signup-success': typeof SignupSuccessRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(authenticated)/settings': typeof authenticatedSettingsRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/seasons/': typeof authenticatedSeasonsIndexRoute
  '/(authenticated)/teams/': typeof authenticatedTeamsIndexRoute
  '/(authenticated)/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/(authenticated)/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/(authenticated)/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/(authenticated)/seasons/$seasonId/': typeof authenticatedSeasonsSeasonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipos'
    | '/signup-form'
    | '/signup-success'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/settings'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/'
    | '/seasons'
    | '/teams'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipos'
    | '/signup-form'
    | '/signup-success'
    | '/login'
    | '/signup'
    | '/settings'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard'
    | '/seasons'
    | '/teams'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/equipos'
    | '/signup-form'
    | '/signup-success'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/(authenticated)/settings'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/seasons/'
    | '/(authenticated)/teams/'
    | '/(authenticated)/seasons/$seasonId/build'
    | '/(authenticated)/seasons/$seasonId/configure'
    | '/(authenticated)/seasons/$seasonId/generate'
    | '/(authenticated)/seasons/$seasonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  EquiposRoute: typeof EquiposRoute
  SignupFormRoute: typeof SignupFormRoute
  SignupSuccessRoute: typeof SignupSuccessRoute
  ApiTeamPdfRoute: typeof ApiTeamPdfRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-form': {
      id: '/signup-form'
      path: '/signup-form'
      fullPath: '/signup-form'
      preLoaderRoute: typeof SignupFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-success': {
      id: '/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-pdf': {
      id: '/api/team-pdf'
      path: '/api/team-pdf'
      fullPath: '/api/team-pdf'
      preLoaderRoute: typeof ApiTeamPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/teams/': {
      id: '/(authenticated)/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof authenticatedTeamsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/': {
      id: '/(authenticated)/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof authenticatedSeasonsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/seasons/$seasonId/': {
      id: '/(authenticated)/seasons/$seasonId/'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/generate': {
      id: '/(authenticated)/seasons/$seasonId/generate'
      path: '/seasons/$seasonId/generate'
      fullPath: '/seasons/$seasonId/generate'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdGenerateRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/configure': {
      id: '/(authenticated)/seasons/$seasonId/configure'
      path: '/seasons/$seasonId/configure'
      fullPath: '/seasons/$seasonId/configure'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdConfigureRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/build': {
      id: '/(authenticated)/seasons/$seasonId/build'
      path: '/seasons/$seasonId/build'
      fullPath: '/seasons/$seasonId/build'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdBuildRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  authenticatedSettingsRoute: typeof authenticatedSettingsRoute
  authenticatedSeasonsIndexRoute: typeof authenticatedSeasonsIndexRoute
  authenticatedTeamsIndexRoute: typeof authenticatedTeamsIndexRoute
  authenticatedSeasonsSeasonIdBuildRoute: typeof authenticatedSeasonsSeasonIdBuildRoute
  authenticatedSeasonsSeasonIdConfigureRoute: typeof authenticatedSeasonsSeasonIdConfigureRoute
  authenticatedSeasonsSeasonIdGenerateRoute: typeof authenticatedSeasonsSeasonIdGenerateRoute
  authenticatedSeasonsSeasonIdIndexRoute: typeof authenticatedSeasonsSeasonIdIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  authenticatedSettingsRoute: authenticatedSettingsRoute,
  authenticatedSeasonsIndexRoute: authenticatedSeasonsIndexRoute,
  authenticatedTeamsIndexRoute: authenticatedTeamsIndexRoute,
  authenticatedSeasonsSeasonIdBuildRoute:
    authenticatedSeasonsSeasonIdBuildRoute,
  authenticatedSeasonsSeasonIdConfigureRoute:
    authenticatedSeasonsSeasonIdConfigureRoute,
  authenticatedSeasonsSeasonIdGenerateRoute:
    authenticatedSeasonsSeasonIdGenerateRoute,
  authenticatedSeasonsSeasonIdIndexRoute:
    authenticatedSeasonsSeasonIdIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  EquiposRoute: EquiposRoute,
  SignupFormRoute: SignupFormRoute,
  SignupSuccessRoute: SignupSuccessRoute,
  ApiTeamPdfRoute: ApiTeamPdfRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
