/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiTeamPdfRouteImport } from './routes/api/team-pdf'
import { Route as ApiPlayoffEventPdfRouteImport } from './routes/api/playoff-event-pdf'
import { Route as ApiEventPdfRouteImport } from './routes/api/event-pdf'
import { Route as publicSignupSuccessRouteImport } from './routes/(public)/signup-success'
import { Route as publicSignupFormRouteImport } from './routes/(public)/signup-form'
import { Route as publicEquiposRouteImport } from './routes/(public)/equipos'
import { Route as authenticatedAdminRouteImport } from './routes/(authenticated)/admin'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as publicPosicionesIndexRouteImport } from './routes/(public)/posiciones/index'
import { Route as authenticatedSeasonsIndexRouteImport } from './routes/(authenticated)/seasons/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as publicPosicionesSeasonIdRouteImport } from './routes/(public)/posiciones/$seasonId'
import { Route as authenticatedSeasonsNewRouteImport } from './routes/(authenticated)/seasons/new'
import { Route as authenticatedSeasonsSeasonIdRouteRouteImport } from './routes/(authenticated)/seasons/$seasonId/route'
import { Route as authenticatedSeasonsSeasonIdIndexRouteImport } from './routes/(authenticated)/seasons/$seasonId/index'
import { Route as authenticatedSeasonsSeasonIdTeamsRouteImport } from './routes/(authenticated)/seasons/$seasonId/teams'
import { Route as authenticatedSeasonsSeasonIdSettingsRouteImport } from './routes/(authenticated)/seasons/$seasonId/settings'
import { Route as authenticatedSeasonsSeasonIdScorecardRouteImport } from './routes/(authenticated)/seasons/$seasonId/scorecard'
import { Route as authenticatedSeasonsSeasonIdPlayoffsRouteImport } from './routes/(authenticated)/seasons/$seasonId/playoffs'
import { Route as authenticatedSeasonsSeasonIdGenerateRouteImport } from './routes/(authenticated)/seasons/$seasonId/generate'
import { Route as authenticatedSeasonsSeasonIdConfigureRouteImport } from './routes/(authenticated)/seasons/$seasonId/configure'
import { Route as authenticatedSeasonsSeasonIdBuildRouteImport } from './routes/(authenticated)/seasons/$seasonId/build'
import { Route as authenticatedSeasonsSeasonIdPlayoffsScorecardRouteImport } from './routes/(authenticated)/seasons/$seasonId/playoffs_.scorecard'
import { Route as authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport } from './routes/(authenticated)/seasons/$seasonId/playoffs_.build'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamPdfRoute = ApiTeamPdfRouteImport.update({
  id: '/api/team-pdf',
  path: '/api/team-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffEventPdfRoute = ApiPlayoffEventPdfRouteImport.update({
  id: '/api/playoff-event-pdf',
  path: '/api/playoff-event-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventPdfRoute = ApiEventPdfRouteImport.update({
  id: '/api/event-pdf',
  path: '/api/event-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupSuccessRoute = publicSignupSuccessRouteImport.update({
  id: '/signup-success',
  path: '/signup-success',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignupFormRoute = publicSignupFormRouteImport.update({
  id: '/signup-form',
  path: '/signup-form',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicEquiposRoute = publicEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedAdminRoute = authenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publicPosicionesIndexRoute = publicPosicionesIndexRouteImport.update({
  id: '/posiciones/',
  path: '/posiciones/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedSeasonsIndexRoute =
  authenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPosicionesSeasonIdRoute =
  publicPosicionesSeasonIdRouteImport.update({
    id: '/posiciones/$seasonId',
    path: '/posiciones/$seasonId',
    getParentRoute: () => publicRouteRoute,
  } as any)
const authenticatedSeasonsNewRoute = authenticatedSeasonsNewRouteImport.update({
  id: '/seasons/new',
  path: '/seasons/new',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedSeasonsSeasonIdRouteRoute =
  authenticatedSeasonsSeasonIdRouteRouteImport.update({
    id: '/seasons/$seasonId',
    path: '/seasons/$seasonId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdIndexRoute =
  authenticatedSeasonsSeasonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdTeamsRoute =
  authenticatedSeasonsSeasonIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdSettingsRoute =
  authenticatedSeasonsSeasonIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdScorecardRoute =
  authenticatedSeasonsSeasonIdScorecardRouteImport.update({
    id: '/scorecard',
    path: '/scorecard',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdPlayoffsRoute =
  authenticatedSeasonsSeasonIdPlayoffsRouteImport.update({
    id: '/playoffs',
    path: '/playoffs',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdGenerateRoute =
  authenticatedSeasonsSeasonIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdConfigureRoute =
  authenticatedSeasonsSeasonIdConfigureRouteImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdBuildRoute =
  authenticatedSeasonsSeasonIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdPlayoffsScorecardRoute =
  authenticatedSeasonsSeasonIdPlayoffsScorecardRouteImport.update({
    id: '/playoffs_/scorecard',
    path: '/playoffs/scorecard',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)
const authenticatedSeasonsSeasonIdPlayoffsBuildRoute =
  authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport.update({
    id: '/playoffs_/build',
    path: '/playoffs/build',
    getParentRoute: () => authenticatedSeasonsSeasonIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/admin': typeof authenticatedAdminRoute
  '/equipos': typeof publicEquiposRoute
  '/signup-form': typeof publicSignupFormRoute
  '/signup-success': typeof publicSignupSuccessRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/playoff-event-pdf': typeof ApiPlayoffEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/': typeof publicIndexRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  '/seasons/new': typeof authenticatedSeasonsNewRoute
  '/posiciones/$seasonId': typeof publicPosicionesSeasonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/seasons/': typeof authenticatedSeasonsIndexRoute
  '/posiciones/': typeof publicPosicionesIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/seasons/$seasonId/settings': typeof authenticatedSeasonsSeasonIdSettingsRoute
  '/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/seasons/$seasonId/': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/playoffs/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
  '/seasons/$seasonId/playoffs/scorecard': typeof authenticatedSeasonsSeasonIdPlayoffsScorecardRoute
}
export interface FileRoutesByTo {
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/admin': typeof authenticatedAdminRoute
  '/equipos': typeof publicEquiposRoute
  '/signup-form': typeof publicSignupFormRoute
  '/signup-success': typeof publicSignupSuccessRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/playoff-event-pdf': typeof ApiPlayoffEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/': typeof publicIndexRoute
  '/seasons/new': typeof authenticatedSeasonsNewRoute
  '/posiciones/$seasonId': typeof publicPosicionesSeasonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/seasons': typeof authenticatedSeasonsIndexRoute
  '/posiciones': typeof publicPosicionesIndexRoute
  '/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/seasons/$seasonId/settings': typeof authenticatedSeasonsSeasonIdSettingsRoute
  '/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/playoffs/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
  '/seasons/$seasonId/playoffs/scorecard': typeof authenticatedSeasonsSeasonIdPlayoffsScorecardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(authenticated)/admin': typeof authenticatedAdminRoute
  '/(public)/equipos': typeof publicEquiposRoute
  '/(public)/signup-form': typeof publicSignupFormRoute
  '/(public)/signup-success': typeof publicSignupSuccessRoute
  '/api/event-pdf': typeof ApiEventPdfRoute
  '/api/playoff-event-pdf': typeof ApiPlayoffEventPdfRoute
  '/api/team-pdf': typeof ApiTeamPdfRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/seasons/$seasonId': typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  '/(authenticated)/seasons/new': typeof authenticatedSeasonsNewRoute
  '/(public)/posiciones/$seasonId': typeof publicPosicionesSeasonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/seasons/': typeof authenticatedSeasonsIndexRoute
  '/(public)/posiciones/': typeof publicPosicionesIndexRoute
  '/(authenticated)/seasons/$seasonId/build': typeof authenticatedSeasonsSeasonIdBuildRoute
  '/(authenticated)/seasons/$seasonId/configure': typeof authenticatedSeasonsSeasonIdConfigureRoute
  '/(authenticated)/seasons/$seasonId/generate': typeof authenticatedSeasonsSeasonIdGenerateRoute
  '/(authenticated)/seasons/$seasonId/playoffs': typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  '/(authenticated)/seasons/$seasonId/scorecard': typeof authenticatedSeasonsSeasonIdScorecardRoute
  '/(authenticated)/seasons/$seasonId/settings': typeof authenticatedSeasonsSeasonIdSettingsRoute
  '/(authenticated)/seasons/$seasonId/teams': typeof authenticatedSeasonsSeasonIdTeamsRoute
  '/(authenticated)/seasons/$seasonId/': typeof authenticatedSeasonsSeasonIdIndexRoute
  '/(authenticated)/seasons/$seasonId/playoffs_/build': typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
  '/(authenticated)/seasons/$seasonId/playoffs_/scorecard': typeof authenticatedSeasonsSeasonIdPlayoffsScorecardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin'
    | '/equipos'
    | '/signup-form'
    | '/signup-success'
    | '/api/event-pdf'
    | '/api/playoff-event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/'
    | '/seasons/$seasonId'
    | '/seasons/new'
    | '/posiciones/$seasonId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/'
    | '/seasons/'
    | '/posiciones/'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId/playoffs'
    | '/seasons/$seasonId/scorecard'
    | '/seasons/$seasonId/settings'
    | '/seasons/$seasonId/teams'
    | '/seasons/$seasonId/'
    | '/seasons/$seasonId/playoffs/build'
    | '/seasons/$seasonId/playoffs/scorecard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/equipos'
    | '/signup-form'
    | '/signup-success'
    | '/api/event-pdf'
    | '/api/playoff-event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/'
    | '/seasons/new'
    | '/posiciones/$seasonId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard'
    | '/seasons'
    | '/posiciones'
    | '/seasons/$seasonId/build'
    | '/seasons/$seasonId/configure'
    | '/seasons/$seasonId/generate'
    | '/seasons/$seasonId/playoffs'
    | '/seasons/$seasonId/scorecard'
    | '/seasons/$seasonId/settings'
    | '/seasons/$seasonId/teams'
    | '/seasons/$seasonId'
    | '/seasons/$seasonId/playoffs/build'
    | '/seasons/$seasonId/playoffs/scorecard'
  id:
    | '__root__'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/(authenticated)/admin'
    | '/(public)/equipos'
    | '/(public)/signup-form'
    | '/(public)/signup-success'
    | '/api/event-pdf'
    | '/api/playoff-event-pdf'
    | '/api/team-pdf'
    | '/api/upload-image'
    | '/(public)/'
    | '/(authenticated)/seasons/$seasonId'
    | '/(authenticated)/seasons/new'
    | '/(public)/posiciones/$seasonId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/seasons/'
    | '/(public)/posiciones/'
    | '/(authenticated)/seasons/$seasonId/build'
    | '/(authenticated)/seasons/$seasonId/configure'
    | '/(authenticated)/seasons/$seasonId/generate'
    | '/(authenticated)/seasons/$seasonId/playoffs'
    | '/(authenticated)/seasons/$seasonId/scorecard'
    | '/(authenticated)/seasons/$seasonId/settings'
    | '/(authenticated)/seasons/$seasonId/teams'
    | '/(authenticated)/seasons/$seasonId/'
    | '/(authenticated)/seasons/$seasonId/playoffs_/build'
    | '/(authenticated)/seasons/$seasonId/playoffs_/scorecard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiEventPdfRoute: typeof ApiEventPdfRoute
  ApiPlayoffEventPdfRoute: typeof ApiPlayoffEventPdfRoute
  ApiTeamPdfRoute: typeof ApiTeamPdfRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-pdf': {
      id: '/api/team-pdf'
      path: '/api/team-pdf'
      fullPath: '/api/team-pdf'
      preLoaderRoute: typeof ApiTeamPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff-event-pdf': {
      id: '/api/playoff-event-pdf'
      path: '/api/playoff-event-pdf'
      fullPath: '/api/playoff-event-pdf'
      preLoaderRoute: typeof ApiPlayoffEventPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event-pdf': {
      id: '/api/event-pdf'
      path: '/api/event-pdf'
      fullPath: '/api/event-pdf'
      preLoaderRoute: typeof ApiEventPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup-success': {
      id: '/(public)/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof publicSignupSuccessRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/signup-form': {
      id: '/(public)/signup-form'
      path: '/signup-form'
      fullPath: '/signup-form'
      preLoaderRoute: typeof publicSignupFormRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/equipos': {
      id: '/(public)/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof publicEquiposRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/posiciones/': {
      id: '/(public)/posiciones/'
      path: '/posiciones'
      fullPath: '/posiciones/'
      preLoaderRoute: typeof publicPosicionesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/seasons/': {
      id: '/(authenticated)/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof authenticatedSeasonsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/posiciones/$seasonId': {
      id: '/(public)/posiciones/$seasonId'
      path: '/posiciones/$seasonId'
      fullPath: '/posiciones/$seasonId'
      preLoaderRoute: typeof publicPosicionesSeasonIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/seasons/new': {
      id: '/(authenticated)/seasons/new'
      path: '/seasons/new'
      fullPath: '/seasons/new'
      preLoaderRoute: typeof authenticatedSeasonsNewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId': {
      id: '/(authenticated)/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/': {
      id: '/(authenticated)/seasons/$seasonId/'
      path: '/'
      fullPath: '/seasons/$seasonId/'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/teams': {
      id: '/(authenticated)/seasons/$seasonId/teams'
      path: '/teams'
      fullPath: '/seasons/$seasonId/teams'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdTeamsRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/settings': {
      id: '/(authenticated)/seasons/$seasonId/settings'
      path: '/settings'
      fullPath: '/seasons/$seasonId/settings'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdSettingsRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/scorecard': {
      id: '/(authenticated)/seasons/$seasonId/scorecard'
      path: '/scorecard'
      fullPath: '/seasons/$seasonId/scorecard'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdScorecardRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/playoffs': {
      id: '/(authenticated)/seasons/$seasonId/playoffs'
      path: '/playoffs'
      fullPath: '/seasons/$seasonId/playoffs'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdPlayoffsRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/generate': {
      id: '/(authenticated)/seasons/$seasonId/generate'
      path: '/generate'
      fullPath: '/seasons/$seasonId/generate'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdGenerateRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/configure': {
      id: '/(authenticated)/seasons/$seasonId/configure'
      path: '/configure'
      fullPath: '/seasons/$seasonId/configure'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdConfigureRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/build': {
      id: '/(authenticated)/seasons/$seasonId/build'
      path: '/build'
      fullPath: '/seasons/$seasonId/build'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdBuildRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/playoffs_/scorecard': {
      id: '/(authenticated)/seasons/$seasonId/playoffs_/scorecard'
      path: '/playoffs/scorecard'
      fullPath: '/seasons/$seasonId/playoffs/scorecard'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdPlayoffsScorecardRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
    '/(authenticated)/seasons/$seasonId/playoffs_/build': {
      id: '/(authenticated)/seasons/$seasonId/playoffs_/build'
      path: '/playoffs/build'
      fullPath: '/seasons/$seasonId/playoffs/build'
      preLoaderRoute: typeof authenticatedSeasonsSeasonIdPlayoffsBuildRouteImport
      parentRoute: typeof authenticatedSeasonsSeasonIdRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedSeasonsSeasonIdRouteRouteChildren {
  authenticatedSeasonsSeasonIdBuildRoute: typeof authenticatedSeasonsSeasonIdBuildRoute
  authenticatedSeasonsSeasonIdConfigureRoute: typeof authenticatedSeasonsSeasonIdConfigureRoute
  authenticatedSeasonsSeasonIdGenerateRoute: typeof authenticatedSeasonsSeasonIdGenerateRoute
  authenticatedSeasonsSeasonIdPlayoffsRoute: typeof authenticatedSeasonsSeasonIdPlayoffsRoute
  authenticatedSeasonsSeasonIdScorecardRoute: typeof authenticatedSeasonsSeasonIdScorecardRoute
  authenticatedSeasonsSeasonIdSettingsRoute: typeof authenticatedSeasonsSeasonIdSettingsRoute
  authenticatedSeasonsSeasonIdTeamsRoute: typeof authenticatedSeasonsSeasonIdTeamsRoute
  authenticatedSeasonsSeasonIdIndexRoute: typeof authenticatedSeasonsSeasonIdIndexRoute
  authenticatedSeasonsSeasonIdPlayoffsBuildRoute: typeof authenticatedSeasonsSeasonIdPlayoffsBuildRoute
  authenticatedSeasonsSeasonIdPlayoffsScorecardRoute: typeof authenticatedSeasonsSeasonIdPlayoffsScorecardRoute
}

const authenticatedSeasonsSeasonIdRouteRouteChildren: authenticatedSeasonsSeasonIdRouteRouteChildren =
  {
    authenticatedSeasonsSeasonIdBuildRoute:
      authenticatedSeasonsSeasonIdBuildRoute,
    authenticatedSeasonsSeasonIdConfigureRoute:
      authenticatedSeasonsSeasonIdConfigureRoute,
    authenticatedSeasonsSeasonIdGenerateRoute:
      authenticatedSeasonsSeasonIdGenerateRoute,
    authenticatedSeasonsSeasonIdPlayoffsRoute:
      authenticatedSeasonsSeasonIdPlayoffsRoute,
    authenticatedSeasonsSeasonIdScorecardRoute:
      authenticatedSeasonsSeasonIdScorecardRoute,
    authenticatedSeasonsSeasonIdSettingsRoute:
      authenticatedSeasonsSeasonIdSettingsRoute,
    authenticatedSeasonsSeasonIdTeamsRoute:
      authenticatedSeasonsSeasonIdTeamsRoute,
    authenticatedSeasonsSeasonIdIndexRoute:
      authenticatedSeasonsSeasonIdIndexRoute,
    authenticatedSeasonsSeasonIdPlayoffsBuildRoute:
      authenticatedSeasonsSeasonIdPlayoffsBuildRoute,
    authenticatedSeasonsSeasonIdPlayoffsScorecardRoute:
      authenticatedSeasonsSeasonIdPlayoffsScorecardRoute,
  }

const authenticatedSeasonsSeasonIdRouteRouteWithChildren =
  authenticatedSeasonsSeasonIdRouteRoute._addFileChildren(
    authenticatedSeasonsSeasonIdRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  authenticatedAdminRoute: typeof authenticatedAdminRoute
  authenticatedSeasonsSeasonIdRouteRoute: typeof authenticatedSeasonsSeasonIdRouteRouteWithChildren
  authenticatedSeasonsNewRoute: typeof authenticatedSeasonsNewRoute
  authenticatedSeasonsIndexRoute: typeof authenticatedSeasonsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  authenticatedAdminRoute: authenticatedAdminRoute,
  authenticatedSeasonsSeasonIdRouteRoute:
    authenticatedSeasonsSeasonIdRouteRouteWithChildren,
  authenticatedSeasonsNewRoute: authenticatedSeasonsNewRoute,
  authenticatedSeasonsIndexRoute: authenticatedSeasonsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicEquiposRoute: typeof publicEquiposRoute
  publicSignupFormRoute: typeof publicSignupFormRoute
  publicSignupSuccessRoute: typeof publicSignupSuccessRoute
  publicIndexRoute: typeof publicIndexRoute
  publicPosicionesSeasonIdRoute: typeof publicPosicionesSeasonIdRoute
  publicPosicionesIndexRoute: typeof publicPosicionesIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicEquiposRoute: publicEquiposRoute,
  publicSignupFormRoute: publicSignupFormRoute,
  publicSignupSuccessRoute: publicSignupSuccessRoute,
  publicIndexRoute: publicIndexRoute,
  publicPosicionesSeasonIdRoute: publicPosicionesSeasonIdRoute,
  publicPosicionesIndexRoute: publicPosicionesIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiEventPdfRoute: ApiEventPdfRoute,
  ApiPlayoffEventPdfRoute: ApiPlayoffEventPdfRoute,
  ApiTeamPdfRoute: ApiTeamPdfRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
